version: '3'

services:
  php:
    build:
      context: ./php
    command: bash -c "composer install --no-interaction && php-fpm"
    volumes:
      - ../app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
  db:
    container_name: symfony_mysql
    image: mysql
    command: 
      --default-authentication-plugin=mysql_native_password
      --secure_file_priv=""
      --local_infile=1
    restart: always
    env_file:
      - ./init/mysql.env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./init:/mydata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
